# Generated by Django 2.2 on 2021-04-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0002_auto_20210424_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
